language: csharp
mono:
  - 4.2.3

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      dotnet: 1.0.0-preview2-003121
    - os: osx
      osx_image: xcode7.2
      dotnet: 1.0.0-preview2-003121

script:
  - ./build.sh UnitTestsDotNetCore