language: csharp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      mono: 4.2.3
      dotnet: 1.0.0-preview2-003121
    - os: osx
      mono: 4.2.3
      dotnet: 1.0.0-preview2-003121

install:
  - nuget restore Octokit-Mono.sln

script:
  - mono tools/nuget/NuGet.exe restore Octokit-Mono.sln
  - ./build.sh BuildMono
  - ./build.sh
  - dotnet --info
  - ./build.sh UnitTestsDotNetCore
