init:
  - git config --global core.autocrlf input
build_script:
  - cmd: build.cmd BuildApp
  - cmd: build.cmd UnitTests
  - cmd: build.cmd ConventionTests
  - cmd: build.cmd CreatePackages
test: off
nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true
artifacts:
- path: '**\octokit*.nupkg'
